### ISSUE TITLE
typo: IRQF_NONE -> IRQ_NONE

### ISSUE THREAD

**Issue by gurugio** [linux-kernel-labs/linux-kernel-labs.github.io#2]
Hi,
I think there is a typo at:
https://github.com/linux-kernel-labs/linux-kernel-labs.github.io/blob/0475029acc102a00bcbdf0ae23f030bb065150f3/interrupts.html#L931

irq-handler should return IRQ_NONE, not IRQF_NONE.

**Comment by dbaluta** [comment]
Hey,

Thanks for reporting this. I will send a patch to the documentation repo.

**Comment by gurugio** [comment]
Thank you ;-)

**Comment by gurugio** [comment]
I'm not sure who should close the issue.
I closed the issue because I created it.

**Comment by dbaluta** [comment]
That's fine! Thanks a lot for your contribution.
